project:
  type: website

website:
  title: "Mark For Change"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: posts.qmd
      - href: booklist.qmd
      - href: volunteerlist.qmd
    right:
      - icon: youtube
        menu:
          - text: "@MarkGingrass"
            href: https://youtube.com/@markgingrass
      - icon: envelope-arrow-up-fill
        href: "mailto:vote@markgingrass.com"  # Ensure correct spacing and quotes
  page-footer: 
    left: "Copyright 2025, Mark Gingrass" 
    right: 
      - icon: envelope-arrow-up-fill
        href: "mailto:vote@markgingrass.com"  # Ensure correct spacing and quotes

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    grid:
      sidebar-width: 150px   # Adjust sidebar width (default ~250px)
      body-width: 1200px      # Change main content width
      margin-width: 200px    # Adjust the margins

editor: visual

freeze: auto

execute:
  freeze: auto