project:
  type: website

website:
  title: "Mark Gingrass"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cyborg
    css: styles.css
    toc: true

editor: visual

freeze: auto

execute:
  freeze: auto

