project:
  type: website

website:
  title: "Mark For Change"
  google-analytics: "G-FY061TKBSB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Meet Mark
        menu:
          - href: about.qmd
            text: About
          - href: resume.qmd
            text: Experience
      - href: posts.qmd
        text: Thoughts & Updates
    right:
      - text: Engage
        menu:
          - href: booklist.qmd
            text: Recommended Reading
          - href: volunteerlist.qmd
            text: Community Involvement
      - icon: youtube
        href: https://www.youtube.com/@markforchange
      - icon: envelope-arrow-up-fill
        href: "contact.html"

format:
  html:
    include-in-header: "ga4.html"
    theme: lux
    css: styles.css
    toc: true
    grid:
      sidebar-width: 150px   # Adjust sidebar width (default ~250px)
      body-width: 1200px      # Change main content width
      margin-width: 200px    # Adjust the margins

editor: visual

freeze: auto

execute:
  freeze: auto