project:
  type: website

website:
  title: "Mark Gingrass"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - posts.qmd

format:
  html:
    theme: solona
    css: styles.css
    toc: true

editor: visual

freeze: auto

execute:
  freeze: auto

